- id: 1
  title: BCAA
  description: Branch-chain amino acids 2-1-1
  # image: /assets/images/cappuccino.jpg
  price: 0.002
  unit: g
  max: 20
  step: 0.1
  fat: 0
  sodium: 0
  protein: 0
  carbs: 0
  dv: N/A
  category: supplement
  ingredients: Sunflower Lecithin
  sans: Soy, Dairy, Yeast, Gluten

- id: 2
  title: Beta Alanine
  description: Beta Alanine
  # image: /assets/images/cappuccino.jpg
  price: 0.002
  unit: g
  max: 20
  step: 05
  fat: 0
  sodium: 0
  protein: 0
  carbs: 0
  dv: 1.2
  category: supplement
  ingredients: 
  sans: Sugar, Soy, Dairy, Yeast, Gluten

- id: 3
  title: Caffeine
  description: Caffeine Anhydrous
  # image: /assets/images/cappuccino.jpg
  price: 0.001
  unit: mg
  max: 0.3
  step: 0.001
  fat: 0
  sodium: 0
  protein: 0
  carbs: 0
  dv: 0,2
  category: supplement
  ingredients: 
  sans: Sugar, Soy, Dairy, Yeast, Gluten

# - id: 1
#   title: Cappuccino
#   description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
#   image: /assets/images/cappuccino.jpg
#   price: 2.99
#   weight: 100
#   maximum-quantity: 10
#   category: coffee
# #  url: https://dragonfruit.jekyll-themes.com #URL of the page where the product is present

# - id: 2
#   title: Espresso
#   description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
#   image: /assets/images/espresso.jpg
#   price: 3.99
#   weight: 100
#   maximum-quantity: 5
#   category: coffee


# - id: 3
#   title: Mocha
#   description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
#   image: /assets/images/black-coffee.jpg
#   price: 2.59
#   weight: 100
#   maximum-quantity: 3
#   category: coffee

# - id: 4
#   title: Oolong Tea
#   description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
#   image: /assets/images/justin-leibow-62-unsplash.jpg
#   price: 3.99
#   weight: 100
#   maximum-quantity: 5
#   category: tea

# - id: 5
#   title: Black Tea
#   description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
#   image: /assets/images/drew-taylor-235558-unsplash.jpg
#   price: 4.19
#   weight: 100
#   maximum-quantity: 5
#   category: tea

# - id: 6
#   title: Fruit Tea
#   description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
#   image: /assets/images/erol-ahmed-305920-unsplash.jpg
#   price: 4.59
#   weight: 100
#   maximum-quantity: 5
#   category: tea

# - id: 7
#   title: Ice Tea
#   description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
#   image: /assets/images/paul-hanaoka-280205-unsplash.jpg
#   price: 4.99
#   weight: 200
#   maximum-quantity: 5
#   category: tea
